site_name: finchGE
repo_url: https://github.com/finchGE/finchge
repo_name: finchge/finchge
extra:
  version:
    provider: mike
theme:
  name: material
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - toc.follow
    - navigation.top
  logo: assets/images/finchge_white.png
  favicon: assets/images/finchge_white.ico
  palette:
    primary: blue
    accent: indigo
nav:
  - Home: index.md
  - Introduction: introduction.md
  - Installation: installation.md
  - Getting Started: getting_started.md
  - Examples: examples.md
  - API Reference: api.md
  - License: license_info.md
  - Contributing: contributing.md
  - Changelog: changelog.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
            show_signature: true
            merge_init_into_class: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: pymdownx.superfences.fence_code_format
        - pymdownx.tabbed:
        - alternate_style: true
  - toc:
      toc_depth: 3
  - pymdownx.highlight:
      use_pygments: true
      pygments_style: material
      linenums: false
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
        generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
